# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://57.129.12.119:3306/crypto_web3?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: Wy1997@Kakarot
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
crypto:
    gmgn:
        token-info-url: https://gmgn.ai/api/v1/mutil_window_token_info
        token-wallet-url: https://gmgn.ai/api/v1/token_wallet_tags_stat
        token-stat-url: https://gmgn.ai/api/v1/token_stat
        token-holders-url: https://gmgn.ai/vas/api/v1/token_holders
        token-security-url: https://gmgn.ai/api/v1/mutil_window_token_security_launchpad
        token-smart-trade-url: https://gmgn.ai/vas/api/v1/token_trades
        wallet-unfollow-url: https://gmgn.ai/api/v1/follow/unfollow_wallet
        wallet-follow-url: https://gmgn.ai/api/v1/follow/follow_wallet
        wallet-activity-url: https://gmgn.ai/vas/api/v1/wallet_activity
        device-id: 5461cc48-2e83-4740-8e90-8409db8cf33d
        client-id: gmgn_web_20250603-1799-730df90
        from-app: gmgn
        app-ver: 20250603-1799-730df90
        tz-name: Asia%2FShanghai
        tz-offset: 28800
        app-lang: zh-CN
        fp-did: 68fd1291b5f4f826d98e6378c0e3a663
        os: web
        limit: 50
        event: buy
        maker:
        tag: smart
        headers:
            User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
            Accept: "application/json, text/plain, */*"
            sentry-trace: "47817276c5b44d07b2627d8c2f221f30-aeb3f1408e5f05b5-0"
            ec-ch-ua-platform: "Windows"
            sec-ch-ua: "Chromium;v=136, Google Chrome;v=136, Not.A/Brand;v=99"
            sec-ch-ua-mobile: "?0"
            baggage: "sentry-environment=production,sentry-release=20250603-1799-730df90,sentry-public_key=93c25bab7246077dc3eb85b59d6e7d40,sentry-trace_id=47817276c5b44d07b2627d8c2f221f30,sentry-sample_rate=0.005,sentry-sampled=false"
            sec-fetch-site: "same-origin"
            sec-fetch-mode: "cors"
            sec-fetch-dest: "empty"
            accept-language: "zh-CN,zh;q=0.9"
            priority: "u=1, i"
            Cookie: "_ga=GA1.1.704572436.1712248135; _ga_0XM0LYXGC8=deleted; b-user-id=f3b3bb30-0b5c-fc55-f1fa-5af0522175ce; GMGN_LOCALE=zh-CN; GMGN_THEME=dark; sid=gmgn%7C691295b013c0e5714ab5f79835145729; _ga_UGLVBMV4Z0=GS1.2.1748597965489087.a12f85a73d09c2e4fe36d46f9d41ade6.QaPK6yv2T4rQ6xjGBTlGnA%3D%3D.jX0Cij%2B%2BT0w5vaKwjl4PnA%3D%3D.lzf%2FKVwJ2Frr9r77jD4QUQ%3D%3D.H3EBykaM5jrX9MGPSyFtfg%3D%3D; GMGN_CHAIN=sol; __cf_bm=9HnOPa4neqo6CA1vYBePh.sI48rtejnAzm5xHZQordU-1748965722-1.0.1.1-atM7ddn7JsqfjPVOix7QEoTpAl4DAAQ69n277jcJJ9bk0vggGlP6dk4rubolKo8QeCDrav7LG2gX_s4N8ukUiGdq_bUvOuq0ySiZOUclslw; cf_clearance=2PgwveiglxlNmOCwrkQgXTEN.tEdWFmJ0fCisOogrIM-1748966032-1.2.1.1-nqhd1Mx2jE49qDWUWtWiBxLB9h0mzwt9OmLfUy48pGOwZuuGVYEElM1YPK.4tnPbyt7Yt6ov3DDrRHp2eagNwywx81TE9JV8AKNt9KUBskZ2wVjvzK4QFRdjzLDjFghz_ApXecOhczoMe8vUtpLV4Z9Jf5omck4Drnh5u4bV1JwlRpAd5CBhvVTI3T0FKZNHCuVVMLEFJiu7_qXx7pshWYIjC9iId3c6nkG64.r5Y91NSK577fRnxSNOPYBe7BMF9OqalS5_dBRERhZosGkSE2st6MiGQJpKdX7mD2Ef0BWmihC3oz9u.tMO5zL956jsekp2Xrc6LW4NayrO_zxUZWxHsN0Mlzv3VhW5txhILbs; _ga_0XM0LYXGC8=GS2.1.s1748966033$o32$g1$t1748966094$j60$l0$h0"
            authorization: "Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiNDVUWGk5NXBCRmlFdUt5RVRlRUgxR0NwN1RuZzl1V0ZobnlxVkVVUkg3eVgiLCJhdWQiOiJnbWduLmFpL2FjY2VzcyIsImNoYWluIjoic29sIiwiZGF0YSI6eyJhZGRyZXNzIjoiNDVUWGk5NXBCRmlFdUt5RVRlRUgxR0NwN1RuZzl1V0ZobnlxVkVVUkg3eVgiLCJhcHAiOiJnbWduIiwiY2hhaW4iOiJzb2wiLCJjbGllbnRfaWQiOiJnbWduX3dlYl8yMDI1MDYwNi0xOTQxLWYyNjU1ZDQiLCJkZXZpY2VfaWQiOiJmODMwNTBhNC04ZTYzLTQ5YjAtYTgyMy1mOTg5NTgxMTZjN2MiLCJmYXRoZXJfaWQiOiI1OTNhNmRmYi0xZTlmLTQzYmMtYjcwNi01MjQ4N2QxZDc1OGYiLCJmaW5nZXJwcmludCI6InYxMGZmYzk2MzA3YWM0YzFmMjM3NTc0ODllNjg5N2QzZjYiLCJwbGF0Zm9ybSI6IndlYiIsInVzZXJfaWQiOiIwYjNhYTY2YmQtMjhkYzEtMjM4NmItODBmZDktMTE3ZmRhZjIifSwiZXhwIjoxNzUwNTYyOTYxLCJpYXQiOjE3NTA1NjExNjEsImlzcyI6ImdtZ24uYWkvc2lnbmVyIiwianRpIjoiYWUyZTJhYzQtNjE4MC00NjM1LWEwMWEtMWM2NmZkYjI2Y2I3IiwibmJmIjoxNzUwNTYxMTYxLCJzdWIiOiJnbWduLmFpL2FjY2VzcyIsInZlciI6IjEuMCIsInZlcnNpb24iOiIyLjAifQ.OtccryMXogQAQDwnlFhybjwN06TKFOlSaic1nEISWjc5fhidamr7ZDOTg5aC6oggVlKEja4Cbey0-bXSDRAexA"
    moralis:
        token-pair-url: https://solana-gateway.moralis.io/token/mainnet/
        pair-info-url: https://solana-gateway.moralis.io/token/mainnet/pairs/
        token-trade-url: https://deep-index.moralis.io/api/v2.2/tokens/
        headers:
            Accept: "application/json"
            X-API-KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjdmYjkxNzAyLTIwY2QtNDVkOS1iNjI5LTY1MzNkMzA2YjA3MCIsIm9yZ0lkIjoiNDUwODc1IiwidXNlcklkIjoiNDYzOTE2IiwidHlwZUlkIjoiOWY1MGNjYTgtODEwNC00NzU0LWI2MDAtYmMyZmM5YzU4MDM5IiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NDkwMjEyMDcsImV4cCI6NDkwNDc4MTIwN30.9RgqquajqDX38Df0EauxayYQcDuiFkkwopD5k0BnOCU"

    axiom:
        token-pair-url: https://api2.axiom.trade/pair-info?pairAddress=
        pair-info-url: https://api2.axiom.trade/token-info?pairAddress=
        headers:
            User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
            Accept: "application/json, text/plain, */*"
            Accept-Encoding: "gzip, deflate, br, zstd"
            ec-ch-ua-platform: "\"Windows\""
            sec-ch-ua: "\"Chromium\";v=\"136\", \"Google Chrome\";v=\"136\", \"Not.A/Brand\";v=\"99\""
            sec-ch-ua-mobile: "?0"
            origin: "https://axiom.trade"
            referer: "https://axiom.trade/"
            sec-fetch-site: "same-origin"
            sec-fetch-mode: "cors"
            sec-fetch-dest: "empty"
            accept-language: "zh-CN,zh;q=0.9"
            priority: "u=1, i"
            Cookie: "auth-refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWZyZXNoVG9rZW5JZCI6IjRhODM5ZWJkLTRlMzUtNDUzMy05ZjdiLTBiMjQ5MDhkODlhNSIsImlhdCI6MTc0ODg4Nzc1OH0.-XRWiCkfcswkGH1-T-neknarXIkVR1zK7YopISLXH30; auth-access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkVXNlcklkIjoiOGQxNmY1OTktNjJlNC00Njk3LTljMTYtZDM0ZmE3M2Y4ZTc2IiwiaWF0IjoxNzQ4OTY0MDI0LCJleHAiOjE3NDg5NjQ5ODR9.hpiLxOeJtIdYkqi5aZFOwbY3qkAv5kLzeeBd9YOc48g"

    dex:
        token-info-url: https://api.dexscreener.com/latest/dex/tokens/

    go-plus:
        token-security-url: https://api.gopluslabs.io/api/v1/solana/token_security?contract_addresses=

proxy:
    http-host: 127.0.0.1
    https-host: 127.0.0.1
    port: 1081

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/crypto/*